# Generated by Django 4.2.17 on 2025-01-05 13:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=50, default='temp-slug'),
            preserve_default=False,
        ),
    ]
